### PR TITLE
Update, add slider and settings

### PR DESCRIPTION
**Pull request by morckx**
This is quite a big pull request, sorry. Basically it does the following:

- upgrade to AndroidX, update gradle and all libraries
- add a big slider for adjusting the zoom level
- add settings for preview resolution, notification sounds, camera selection, max brightness, flashlight on startup
- fix continuous auto focus
- fix distorted preview after resume from suspend on some devices
- reset contrast/color mode on long press

Tested (including snapshot saving) on API 16, 21, 25, 29, 30 

visor

settings

### CODE REVIEW

**Comment by kloener** [comment]
Wow thank you for your contribution. I'll have a look into theses changes. And sorry for the late answer.

**Review by kloener — APPROVED** [review]
Your changes really improve the app. I'll approve this PR. Thank you very much!

A minor issue: If the front camera is selected the color filters invert the image.

**Comment by morckx** [comment]
> Your changes really improve the app. I'll approve this PR. Thank you very much!
> 

Thanks!

> A minor issue: If the front camera is selected the color filters invert the image.

OK, I'll have a look.

**Comment by morckx** [comment]
> 
> > A minor issue: If the front camera is selected the color filters invert the image.
> 
> OK, I'll have a look.

OK, the mirrored preview with selfie camera and active filter should be fixed. It might not be the best solution, but should be OK for the probably rare use cases.

**Pull request merged**
